blockNode:
  config:
    BACKFILL_BLOCK_NODE_SOURCES_PATH: "/opt/hiero/block-node/backfill/block-node-sources.json"
    BACKFILL_FETCH_BATCH_SIZE: "10"
  backfill:
      # The path to the block-node-sources.json file must match the path property in
      # blockNode.config.BACKFILL_BLOCK_NODE_SOURCES_PATH
      path: "/opt/hiero/block-node/backfill"
      filename: "block-node-sources.json"
      sources:
        # note that this is an example of another (source) BN on the same K8 cluster
        # different namespace <serviceName>.<namespace>.svc.cluster.local
        - address: "source-block-node-helm-chart.source.svc.cluster.local"
          port: 40840
          priority: 1
