---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: live-storage-pv
  namespace: <NAMESPACE>
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/fast-storage/live
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: live-storage-pvc
  namespace: <NAMESPACE>
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: live-storage-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: archive-storage-pv
  namespace: <NAMESPACE>
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/fast-storage/archive
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archive-storage-pvc
  namespace: <NAMESPACE>
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: archive-storage-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logging-storage-pv
  namespace: <NAMESPACE>
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/fast-storage/logs
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logging-storage-pvc
  namespace: <NAMESPACE>
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: logging-storage-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: verification-storage-pv
  namespace: <NAMESPACE>
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/fast-storage/verification
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verification-storage-pvc
  namespace: <NAMESPACE>
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: verification-storage-pv
