resources:
  requests:
    cpu: "8"
    memory: "12Gi"

blockNode:
  config:
    JAVA_OPTS: '-Xms8G -Xmx8G -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="/tmp/dump.hprof"'
    MESSAGING_BLOCK_ITEM_QUEUE_SIZE: "1024"
    MESSAGING_BLOCK_NOTIFICATION_QUEUE_SIZE: "64"
    BACKFILL_FETCH_BATCH_SIZE: "20"
  persistence:
    archive:
      size: 16Gi
    live:
      size: 4Gi
    logging:
      size: 2Gi
    verification:
      size: 500Mi
  health:
    readiness:
      initialDelaySeconds: 10
      timeoutSeconds: 2
    liveness:
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 2
      successThreshold: 1
      failureThreshold: 3
