plugins:
  volumeName: "plugins"
  size: 2Gi
  enabled: true
  names: "facility-messaging,block-access-service,health,server-status,stream-publisher,stream-subscriber,verification,blocks-file-recent,backfill,s3-archive"
