services:
  simulator-publisher:
    container_name: simulator-publisher
    build:
      context: .
      dockerfile: Dockerfile
    image: hedera-block-simulator:latest
    networks:
      - block-node_default
    ports:
      - "5006:5006"
    env_file:
      - .env
    environment:
      - BLOCK_STREAM_SIMULATOR_MODE=${PUBLISHER_BLOCK_STREAM_SIMULATOR_MODE}
      - PROMETHEUS_ENDPOINT_PORT_NUMBER=${PUBLISHER_PROMETHEUS_ENDPOINT_PORT_NUMBER}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9998/metrics"]
      interval: 3s
      timeout: 10s
      retries: 5
    volumes:
      - simulator_data:/opt/simulator/data

networks:
  block-node_default:
    name: block-node_default
    external: true

volumes:
  simulator_data: